klaytn/klaytn-docs

.github/ISSUE_TEMPLATE/content_contribution.md
.github/PULL_REQUEST_TEMPLATE.md

- fixed the content contribution issue template
- added the pr template

392-fixing-the-content-creation-template

---

docs/SUMMARY.md
docs/node/download/v1.8.0.md

Add v1.8.0 download page

---

docs/node/download/README.md

I missed one page that needs to be updated for v1.8.0 download page. 
Related PR: https://github.com/klaytn/klaytn-docs/pull/394

Update download readme page for v1.8.0 

---

docs/SUMMARY.md
docs/node/download/README.md
docs/node/download/v1.8.1.md

- Add v1.8.1 download page.
https://github.com/klaytn/klaytn/releases/tag/v1.8.1

add v1.8.1 download page

---

docs/SUMMARY.md
docs/node/download/README.md
docs/node/download/v1.8.2.md

Add Klaytn v1.8.2 download page

Add Klaytn v1.8.2 download page

---

docs/dapp/sdk/caver-js/getting-started.md
docs/dapp/sdk/caver-js/v1.4.1/getting-started_1.4.1.md
docs/dapp/tutorials/count-bapp/6.-deploy-contract.md
docs/dapp/tutorials/fee-delegation-example.md
docs/dapp/tutorials/migrating-ethereum-app-to-klaytn.md
docs/smart-contract/deploy-guide.md

Changed testnet url from `https://your.en.url:8651` to `https://api.baobab.klaytn.net:8651`

url change

---

docs/dapp/json-rpc/api-references/personal.md

This PR removes `optional` with the non-optional parameter.
To use `personal_sign` you need to pass the passphrase as a  last parameter.

Removed optional

---

docs/languages.md

Deleted the outdated crowdin leaderboard

deleted leaderboard

---

docs/dapp/json-rpc/api-references/eth/block.md

When fetching uncle count for non-existing block, apis return `null`.
Related PR at Klaytn: https://github.com/klaytn/klaytn/pull/1267

Update content for apis fetching uncle count

---

docs/dapp/json-rpc/api-references/klay.md
docs/dapp/json-rpc/api-references/klay/block.md

This API is not supported now. I checked Klaytn source code and called actual rpc call to node.
Please let me know If I missed something. 
- [ x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-docs)

Remove klay_minig from klaytn docs

---

docs/dapp/json-rpc/api-references/eth/block.md

Related PR: https://github.com/klaytn/klaytn/pull/1261

Returns null when there is no matching block

---

docs/klaytn/why-klaytn.md

- Update on the Exponential term of the transaction cost calculation
https://github.com/klaytn/klaytn-docs/issues/429
N/A

updated the exponential term phrased in the transaction cost calculation

---

docs/dapp/json-rpc/api-references/eth/config.md
docs/dapp/json-rpc/api-references/eth/gas.md
docs/dapp/json-rpc/api-references/klay/config.md
docs/klaytn/design/computation/execution-model.md
docs/klaytn/design/transaction-fees/transaction-fees-previous.md
docs/klaytn/design/transaction-fees/transaction-fees.md
docs/smart-contract/sample-contracts/erc-20/2-erc20.md
docs/smart-contract/sample-contracts/erc-721/2-erc721.md

Gas price change, (will wait until 4/3)

Change gpeb to ston

---

docs/SUMMARY.md
docs/klaytn-history/README.md
docs/node/download/README.md
docs/smart-contract/porting-ethereum-contract.md
docs/smart-contract/solidity-smart-contract-language.md

Hf history

---

docs/klaytn/design/accounts.md
docs/klaytn/design/computation/computation-cost/computation-cost.md
docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine.md
docs/klaytn/design/transaction-fees/transaction-fees.md
docs/smart-contract/precompiled-contracts/precompiled-contracts.md

Update Istanbul hardfork block number on Cypress network. 
I also make an issue requesting a new page describing hardfork history and blocknumbers in https://github.com/klaytn/klaytn-docs/issues/419

Update protocol update block number on various contents

---

docs/SUMMARY.md
docs/node/download/README.md
docs/node/download/v1.8.3.md

Add Klaytn v1.8.3 download page

Add Klaytn v1.8.3 download page

---

docs/SUMMARY.md
docs/dapp/developer-tools/README.md
docs/toolkit/covalent.md

Added the updated description for Covalent on Developer TOols and also truffle, because it was missing?

Covalent_dev_tools

---

docs/SUMMARY.md
docs/node/download/README.md
docs/node/download/v1.8.4.md

Add Klaytn v1.8.4 download page.
We are uploading files now for download links.

Add Klaytn v1.8.4 download page

---

docs/dapp/json-rpc/public-en.md

new fantrie endpoints

---

docs/README.md

To maximize the visibility of awesome klaytn, I added it in the welcome page.

Awesome Klaytn

---

docs/node/service-chain/references/genesis.md

- fixed mismatch descriptions in genesis.md

Fixed mismatch descriptions in genesis

---

docs/dapp/json-rpc/public-en.md

From All That Node
Add new endpoints from All That Node

Add new endpoints(mainnet & testnet)

---

docs/dapp/json-rpc/api-references/governance.md
docs/dapp/sdk/caver-js/api-references/caver.rpc/governance.md

We have renamed PoC to KGF (Reference: https://docs.klaytn.foundation/klaytn2/massive-ecofund) .
However, node API doesn't change it to KGF yet.
So, I change back to PoC for an API return field. This name will be updated when the API return field is updated later.
API return example
```
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"BlockNum": 94867200,
"CouncilNodeAddrs": [
"0x99fb17d324fa0e07f23b49d09028ac0919414db6",
"0x571e53df607be97431a5bbefca1dffe5aef56f4d",
"0xb74ff9dea397fe9e231df545eb53fe2adf776cb2",
"0x5cb1a7dccbd0dc446e3640898ede8820368554c8",
"0x776817c0ef3d06d794cf01ae9afa33d7397b9b40",
"0xc180ca565b34b5b63877674f5fe647e7da079022",
"0x03497f51c31fe8b402df0bde90fd5a85f87aa943",
"0xfb416e2a714a5d1e034beacf0646a36876b72765",
"0xd6d7762dd7fadf0512d83d0143685fc85488b64e", …
```

Update KGF to PoC

---

docs/dapp/json-rpc/public-en.md

- Update endpoints for better visibility

Update endpoints for better visibility

---

docs/dapp/sdk/caver-js/README.md
docs/dapp/sdk/caver-js/api-references/caver.rpc/governance.md
docs/dapp/sdk/caver-js/api-references/caver.rpc/klay.md
docs/dapp/sdk/caver-js/api-references/caver.transaction/README.md

This PR includes caver-js v1.9.0 features.
- `effectiveGasPrice` field is added in tx receipt
- Newly introduced `tx.suggestedGasPrice`
- Newly added `caver.rpc.klay.getLowerBoundGasPrice` and `caver.rpc.klay.getUpperBoundGasPrice`

Added docs contents for caver-js v1.9.0

---

docs/dapp/json-rpc/api-references/governance.md

- Add the new KIP71 parameters to Governance API docs.
https://github.com/klaytn/klaytn-docs/issues/457

Add kip71 items to rpc/governance

---

docs/SUMMARY.md
docs/dapp/json-rpc/api-references/klay.md

Gas related klay namespace APIs were not exposed and the links were not correct.

Fixed API link

---

docs/SUMMARY.md
docs/node/download/README.md
docs/node/download/v1.9.0.md

Add a download page for v1.9.0

Add a download page for v1.9.0

---

docs/smart-contract/porting-ethereum-contract.md

- Update EVM version of Cypress

Update EVM version of Cypress

---

docs/SUMMARY.md
docs/node/download/README.md
docs/node/download/v1.9.1.md

Add v1.9.1 download page

---

docs/klaytn-history/README.md

- Added magma hard fork history
- #475

added magma hardfork history

---

docs/dapp/sdk/caver-js/api-references/caver.kct/kip17.md
docs/dapp/sdk/caver-js/api-references/caver.kct/kip37.md
docs/dapp/sdk/caver-js/api-references/caver.kct/kip7.md
docs/smart-contract/solidity-smart-contract-language.md
docs/smart-contract/token-standard.md

- Updated the old links (kip, truffle)

resolved old links

---

docs/dapp/json-rpc/api-references/klay/config.md
docs/dapp/sdk/caver-js/api-references/caver.rpc/klay.md
docs/dapp/sdk/caver-js/v1.4.1/api-references/caver.klay/config.md

- Added current version contents of `klay_protocolVersion` API.

updated current version of Klaytn protocol

---

docs/dapp/tutorials/fee-delegation-example.md

- Changed some constant values to variables for better understanding.

Update sample code

---

docs/dapp/json-rpc/public-en.md

Update Klaytn Foundation public-en.md

---

docs/klaytn/design/transaction-fees/transaction-fees.md

* Updated 'transaction fees' explanation for dynamic gas fee mechanism and base fee.

Update 'transaction fees' page for dynamic gas fee mechanism

---

docs/dapp/tutorials/fee-delegation-example.md

- This PR fixes a few spelling errors in fee-delegation-example.md file
- None.
- None

docs: fix spelling errors

---

docs/dapp/tutorials/count-dapp/1.-environment-setup.md
docs/dapp/tutorials/count-dapp/4.-write-smart-contract.md
docs/dapp/tutorials/count-dapp/5.-frontend-code-overview/README.md
docs/dapp/tutorials/count-dapp/6.-deploy-contract.md
docs/dapp/tutorials/klaystagram/1.-environment-setup.md
docs/dapp/tutorials/klaystagram/2.-clone-klaystagram-dapp.md
docs/dapp/tutorials/klaystagram/4.-write-klaystagram-smart-contract.md
docs/dapp/tutorials/klaystagram/5.-deploy-contract.md
docs/dapp/tutorials/klaystagram/README.md

- Updated for more visibility (e.g., contents number, highlight the sentence)

Update for more visibility

---

.github/CODEOWNERS

Code-owners

---

docs/dapp/sdk/caver-js/api-references/caver.rpc/klay.md

Added Comma

---

docs/klaytn/README.md
docs/klaytn/design/token-economy.md
docs/toolkit/klaytnscope.md

block reward change

---

docs/dapp/json-rpc/public-en.md

fantrie node name change

---

docs/installation-guide/deployment/core-cell/installation-guide/download.md
docs/installation-guide/deployment/endpoint-node/installation-guide/download.md
docs/installation-guide/deployment/service-chain/getting-started/4nodes-setup-guide.md
docs/installation-guide/deployment/service-chain/references/download.md

fixed broken link

---

docs/installation-guide/deployment/endpoint-node/installation-guide/download.md

Fix a broken link.
BTW, there are too many depths in this menu path. @terry-klaytn Can we refine the menu structure? 

Fix a broken link

---

docs/SUMMARY.md
docs/dapp/rpc-service.md

Added Rpc service page

---

docs/operation-guide/chaindata-change.md

update disk size guide

---

docs/dapp/json-rpc/api-references/governance.md

- introduce new governance_chainConfigAt()
- update chainConfig description
FYI, see https://github.com/klaytn/klaytn/pull/1704

Add chainConfigAt, modify chainConfig

---

docs/SUMMARY.md
docs/installation-guide/download/README.md
docs/installation-guide/download/v1.10.0.md

- update download page for v1.10.0

V1.10.0 release

---

docs/SUMMARY.md
docs/installation-guide/download/README.md
docs/installation-guide/download/v.1.10.1.md

- add v1.10.1 binary release page 
- 

add binary download page for release v1.10.1

---

docs/dapp/json-rpc/public-en.md

Update EN RPC

---

docs/dapp/json-rpc/public-en.md

change text json rpc endpoints

---

docs/dapp/json-rpc/public-en.md

update archive node info into klaytn-docs

---

docs/SUMMARY.md
docs/installation-guide/download/README.md
docs/installation-guide/download/v1.10.2.md

- add v1.10.2 download page in docs

add v1.10.2 release download page

---

docs/dapp/json-rpc/api-references/eth/transaction.md

Fix typo: `klay_estimateGas` -> `eth_estimateGas`

---

docs/installation-guide/deployment/core-cell/system-requirements.md

add the medium link explaining how the hw spec is decided

---

docs/misc/klaytn-history.md

- remove estimate time for KIP103, Kore Hardfork and add actual time

add actual time for harforks

---

docs/dapp/json-rpc/api-references/governance.md

- Reflect changes https://github.com/klaytn/klaytn/pull/1783
- Contains the changes of #514.

Governance API changes in v1.10.2

---

docs/dapp/sdk/web3-js.md

- Fixed minor typos and codes to run web3-js tutorial

sdk: updated web3-js.md

---

docs/klaytn/design/storage.md

- Link state migration explanation page and operation guide page

Link state migration explanation page and operation guide page

---

docs/dapp/json-rpc/api-references/admin.md
docs/dapp/json-rpc/api-references/eth.md
docs/dapp/json-rpc/api-references/eth/transaction.md
docs/dapp/json-rpc/api-references/klay.md
docs/dapp/json-rpc/api-references/klay/misc.md
docs/dapp/json-rpc/api-references/klay/transaction.md

- add eth_resend, klay_resend
- add klay_recoverFromTransaction, klay_recoverFromMessage
- change admin_exportChain
- fix formal typos

Add a few APIs

---

docs/dapp/json-rpc/api-references/governance.md
docs/dapp/json-rpc/api-references/klay.md
docs/dapp/json-rpc/api-references/klay/misc.md

- introduce [klay_forkStatus](https://github.com/klaytn/klaytn/pull/1804), [governance_getRewardsAccumulated](https://github.com/klaytn/klaytn/pull/1848)

Add klay_forkStatus, governance_getRewardsAccumulated APIs

---

docs/installation-guide/download/README.md
docs/installation-guide/download/v1.11.0.md

v1.11.0 rpm package add

---

docs/klaytn/design/computation/computation-cost/computation-cost.md
docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine.md

- PUSH0 opcode added
- hardfork activation change will be applied after shanghai hardfork activation.

PUSH0 opcode add

---

docs/operation-guide/log-management.md

- Update log rotation guide from a shell script to the log rotation function in klaytn introduced in v1.11.0

update log rotation guide

---

docs/dapp/json-rpc/api-references/debug.md
docs/dapp/json-rpc/api-references/debug/tracing.md

add debug_traceCall

---

docs/dapp/rpc-service/public-en.md

pocket-public-rpc added

---

docs/misc/glossary.md

- Added glossary entries to Glossary page
- I'v made this PR for the second time because the original PR (https://github.com/klaytn/klaytn-docs/pull/592) has a problem with CLA signing due to incorrect email configuration in local repo.

Added glossary entries to Glossary page (2nd attempt)

---

docs/klaytn/design/governance.md
docs/klaytn/why-klaytn.md

quick fix on KIR and KGF

---

docs/misc/klaytn-history.md

Klaytn hard fork history updated to reflect the Shanghai hard fork

shanghai-hardfork history added

---

docs/installation-guide/download/README.md
docs/misc/glossary.md

quick fix on package installation and glossary page

quick fix on package installation and glossary page

---

docs/dapp/json-rpc/api-references/eth/transaction.md
docs/dapp/json-rpc/api-references/klay/transaction.md

updated eth_sendRawTransaction to reflect params value

updated rpc-api

---

docs/klaytn/design/storage/live-pruning.md

- updated wrong link in the pruning document.

fixed links of pruning document

---

README.md
docs/toolkit/safepal-s1.md

updates readme and safepalS1 content images

updated readme and safepalS1 content images

---

docs/SUMMARY.md
docs/dapp/developer-tools/indexers/getting-started.md
docs/dapp/developer-tools/indexers/subquery.md
docs/toolkit/subquery.md

Propose to add an Indexer section the Developer Tools and have SubQuery as one of the child pages. 
NA
NA

Add an Indexer section within Developer Tools

---

docs/installation-guide/deployment/core-cell/installation-guide/consensus-node-setup/startup-the-cn.md

Write about the new core cell management task, extracting the BLS public key info.

Core Cell Export BLS public key info

---

docs/SUMMARY.md
docs/installation-guide/download/README.md
docs/installation-guide/download/v1.12.0.md
docs/klaytn/README.md

add-klaytn-v1.12.0

---

.github/workflows/prod.yml

Change namee env of klaytn-docs

update env name

---

i18n/ko/docusaurus-plugin-content-docs/current/build/tools/wallets/wallet-libraries/web3Auth.md

fix wrong conflict

---

docusaurus.config.js

Updated Algolia search API key

---

docusaurus.config.js

Reverted Algolia search API key

---

docs/build/smart-contracts/ide-and-tools/ide-and-tools.md
sidebars.js

ide and tools sections updated

ide and tools updated

---

sidebars.js

account.md was included in the sidebar.js file

accounts added

---

docs/misc/operation/upstream-en.md
sidebars.js

- This article explains how to set up an upstream node of a full mode endpoint node.
- https://github.com/klaytn/klaytn/pull/2013

Set up an upstream node

---

README.md
docusaurus.config.js

Added Klaytn docs platform change notification

---

docs/build/tools/wallets/wallet-libraries/privy.md
docs/references/sdk/caver-js/get-started.md

- typo fix of a reference and a link

typo fix of a reference and a link

---

docs/nodes/downloads/downloads.md
docs/nodes/downloads/v1.12.1.md
sidebars.js

klaytn v1.12.1 added

---

docs/nodes/downloads/v1.12.0.md
sidebars.js

node-download updated

---

docs/build/tools/wallets/wallet-libraries/particle.md

updated minor errors in particle-network section

updated particle-network section

---

docusaurus.config.js

- Resolve the environment variable bugfix

navBar bugfix

---

.github/workflows/prod.yml

- Add generate mdx file on CICD

add generate mdx file on CICD

---

docs/misc/klaytn-history.md

- Hardfork history page contains the hard fork block numbers and its summary.
- This PR updates the hardfork history page about ShanghaiCompatible, CancunCompatible, Randao hardforks.

Update Shanghai,Cancun,Randao hardfork history

---

docs/nodes/core-cell/system-requirements.md
docs/nodes/endpoint-node/system-requirements.md

Add pruning spec

---

docusaurus.config.js

- Enable the copy button on code block

enable copy button on code block

---

docusaurus.config.js

Updated the analytics tracking code with that of self-hosted one because we reached our usage limit of 10,000 free events on the Umami Cloud free plan in the middle of this month and the events after that are no longer being recorded by the end of the month. With self-hosted service, however, there is no usage limit in terms of event collection.
If this is a relatively large content contribution, kick off the …

Updated the analytics tracking code

---

docs/build/get-started/before-you-start.md
docs/build/get-started/hardhat.md
docs/build/smart-contracts/deploy/foundry.md
docs/build/smart-contracts/deploy/ken.md
docs/build/smart-contracts/verify/block-explorers.md
docs/build/smart-contracts/verify/hardhat.md
docs/build/tools/block-explorers/block-explorers.md
docs/build/tools/block-explorers/klaytnscope.md
docs/build/tools/wallets/wallet-libraries/particle.md
docs/build/tools/wallets/wallet-libraries/web3Auth.md
docs/build/tools/wallets/wallet-libraries/web3Modal.md
docs/build/tools/wallets/wallet-libraries/web3Onboard.md
docs/build/tutorials/connecting-metamask.md
docs/build/tutorials/count-dapp/code-overview/count-component.md
docs/build/tutorials/fee-delegation-example.md
docs/build/tutorials/migrating-ethereum-app-to-klaytn.md
docs/build/tutorials/verifying-contracts.md
docs/learn/learn.md
docs/misc/faq.md
package-lock.json

updated connecting-metamask page and  explorer URLs

updated connecting-metamask page and  explorer URLs

---

docs/nodes/core-cell/node-security.md
docs/nodes/core-cell/securing-nodes.md
sidebars.js

- Add the "Securing nodes" page under the Nodes > Core Cell guides.
- It's about general security advice for node operators.
Note to maintainers:
- I tried to build the docs but failed with a "Hook useDoc is called outside the <DocProvider>" error. Therefore I am only submitting a markdown file.
- I want to locate this page in the Core Cell section. Teach me how or configure yourself, please.
```
[Nodes]
Core Cell
System Requirements
Network Configuration
Install Core Cell
Monitor Core Cell
Configure High Availability
Securing Nodes <-- here
```
*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a …

Add Node Security page

---

docs/kaiatech/kaia-white-paper.md

kaia whitepaper appendix removed

---

README.md
docusaurus.config.js

- Add archive notification using announcement bar
- Update README

Add archive notification using announcement bar
